name = "A"
author = "Perchy"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f097fddf27ca58759fd9e15e2fa9a7c042220fbf74736ea769ea843a20e0618"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
